export type WatchlistPlayer = {
  id: string;
  name: string;
  height: string;
  position: string;
  classYear: string;
  school: string;
  state: string;
  stars: number; // 1–5
  summary?: string;
};

  // keep your players exactly as-is below

export const watchlist: WatchlistPlayer[] = [
  // 5★
  {
    id: "jj-andrews-2026",
    name: "JJ Andrews",
    height: "6'7",
    position: "G/F",
    classYear: "2026",
    school: "Little Rock Christian",
    state: "AR",
    stars: 5,
summary: "JJ Andrews is a once-in-a-class, physical scoring wing who immediately sets the tone whenever he steps on the floor. At 6’7 with a 7-foot wingspan and a frame built like a grown man, he dominates downhill, finishes through traffic, and rises for emphatic dunks that change the momentum of a game. His perimeter shot is coming along smoothly (36% 3PT, 72% FT), making him a multi-dimensional scoring threat. Defensively, Andrews is long, aggressive, and versatile — disrupting passing lanes, switching across positions, and consistently elevating his team’s energy. He combines intelligence, effort, and elite physical tools to impact every possession. A University of Arkansas signee, JJ blends strength, athleticism, skill, and an unstoppable mentality, solidifying his spot as the premier prospect in the 2026 class.",
  },
  {
    id: "ethan-sheats-2026",
    name: "Ethan Sheats",
    height: "6'9",
    position: "F/C",
    classYear: "2026",
    school: "Denton HS",
    state: "TX",
    stars: 5,
    summary: "Ethan Sheats is a 6’9 stretch big with fluid athleticism, touch, and expanding versatility. He’s already a threat beyond the arc with smooth shooting mechanics, while his frame and mobility let him operate comfortably both in the paint and on the perimeter. An explosive lob threat with strong finishing instincts, Sheats uses length, timing, and footwork to dominate the interior. He moves with natural fluidity, showing long-term versatility — capable of defending in space, running the floor, and developing into a modern big who can stretch, rim-run, and switch defensively. His ceiling continues to rise as his confidence and consistency grow, projecting him as a high-upside forward with the tools to anchor a frontcourt and stretch defenses. Committed to the University of Omaha, Sheats combines size, skill, and athleticism to make an immediate impact.",
  },

  // 4★
  {
    id: "austin-brown-2026",
    name: "Austin Brown",
    height: "6'5",
    position: "G/F",
    classYear: "2026",
    school: "Maryland Commit",
    state: "MD",
    stars: 4,
    summary:"Austin Brown is arguably the best shooter in his class — a smooth, confident perimeter threat whose touch and form stand out immediately. At 6’5, he brings ideal size for a scoring wing and has built his reputation on consistency, spacing, and shot-making under pressure. His shooting mechanics are clean, repeatable, and effortless — whether off the catch, off movement, or pulling up in rhythm. He stretches defenses and creates gravity the moment he crosses half court. Beyond his jumper, Brown shows improved comfort attacking closeouts and finishing with touch around the rim. Defensively, he competes with effort and positioning, embracing the challenge of guarding bigger wings. His poise and maturity fit the mold of a player who can contribute immediately at the next level.A marksman with confidence and range, Brown’s shooting alone makes him a difference-maker — and his continued growth as a secondary creator only raises his ceiling.",
  },
  {
    id: "zvon-king-2026",
    name: "Zvon King",
    height: "6'5",
    position: "G/F",
    classYear: "2026",
    school: "Hampton Commit",
    state: "TX",
    stars: 4,
    summary:"Zvon King is a pure scorer with high two-way potential and a motor that never quits. After flying under the radar for most of his high school career, he exploded onto the scene last season and over the summer — proving he belongs among the elite. At 6’5 with a long, athletic frame, King can get a bucket from anywhere on the floor. He’s dangerous off the dribble, confident shooting off movement, and thrives attacking gaps with balance and control. His ability to create separation and finish through contact makes him a constant scoring threat at all three levels. He is one of the most skilled perimeter players in Texas, capable of impacting the game anytime he’s on the floor. Defensively, King’s length, athleticism, and effort give him major upside as a perimeter stopper. He competes on every possession and has the tools to guard multiple positions when locked in. A confident, explosive wing who plays with purpose and edge, King’s blend of scoring ability, athleticism, and emerging two-way game make him one of the most intriguing prospects in the 2026 class.",
  },
  {
    id: "trey-rhodes-2026",
    name: "Trey Rhodes",
    height: "6'4",
    position: "G/F",
    classYear: "2026",
    school: "Arkansas HS",
    state: "AR",
    stars: 4,
summary: "Trey Rhodes is a freak of nature — smooth, explosive, and built like he was made for highlight reels. A transfer from Georgia, his game jumps off the floor from the moment the ball tips. He’s physically mature, with elite leaping ability and body control that makes him a matchup nightmare anywhere on the court. Rhodes blends power and finesse seamlessly — an athlete who plays with violence but finishes with touch. He’s dangerous spotting up or attacking off the dribble, forcing defenders to pick their poison. Add in his advanced post game and a perimeter attack that keeps improving, and it’s clear why his stock skyrocketed this past summer. Defensively, he’s versatile enough to guard every position. His mix of strength, lateral quickness, and instincts allow him to switch across matchups and impact the game in every area. A certified problem on both ends, Rhodes’ upside continues to rise — and his best basketball is still ahead of him. Projected Low-Major to Mid-Major, but if he can tap into his potential, he has all the tools to be a 5-star prospect.",
  },
  {
    id: "tk-taylor-2026",
    name: "TK Taylor",
    height: "6'6",
    position: "F",
    classYear: "2026",
    school: "San Angelo Central",
    state: "TX",
    stars: 4,
    summary: "TK Taylor is one of the fastest-rising prospects in Texas — a powerful, explosive 6’6 forward with the physical tools and mentality of a true high-major recruit. He combines size, athleticism, and fluid movement in a way that immediately pops on film and dominates in live action. Taylor attacks the rim with authority, finishing through or above traffic with ease. In transition, he’s a freight train; in the half-court, he thrives as a face-up scorer who gets downhill at will. His growing handle and improved shot creation make him increasingly difficult to contain, and he’s becoming more confident operating both on the wing and in the mid-post. Defensively, Taylor is a major problem. He blocks shots, slides with guards, rebounds in traffic, and uses his strength to eliminate advantages. His versatility lets him guard multiple positions and switch without being exploited — a major calling card at the next level. What makes Taylor even scarier is his trajectory. He’s expanding his perimeter skill, tightening his decision-making, and learning how to consistently impose his will without forcing the game. A two-way force with Division I size, athleticism, and upside, TK Taylor is trending up fast — and his name will only continue to rise as his skill set sharpens.",

  },
  {
    id: "dominic-fulton-2026",
    name: "Dominic Fulton",
    height: "6'4",
    position: "G/F",
    classYear: "2026",
    school: "Plainview HS",
    state: "TX",
    stars: 4,
    summary:"Dominic Fulton is one of the most physically imposing and polished prospects in the region. At 6’4 with elite power, explosiveness, and body control, he plays with a maturity and presence that immediately stands out. Fulton is at his best in attack mode. He applies constant pressure by getting downhill, finishing above defenders, and scoring from all three levels. His offensive versatility is advanced for his age — he can space the floor with the three, create clean midrange looks, or overpower smaller guards and wings in the post. But Fulton’s value goes beyond scoring. He plays a mature, winning brand of basketball. He shares it, understands when to make the extra pass, and competes consistently on both ends. Defensively, his strength and athleticism allow him to guard multiple positions, rotate with purpose, and impact plays with timing and physicality. A vocal competitor with real leadership traits, Fulton already impacts winning at a high level — and still has upside left to tap into. As his perimeter consistency and creation continue to sharpen, expect his recruitment and recognition to rise.",
  },
  {
    id: "cale-clingan-2026",
    name: "Cale Clingan",
    height: "6'9",
    position: "F/C",
    classYear: "2026",
    school: "Derby HS",
    state: "KS",
    stars: 4,
    summary""Cale Clingan is rapidly becoming one of the most intriguing frontcourt prospects in the Midwest — a modern 6’9 big with perimeter skill, mobility, and a growing physical presence. Offensively, Clingan’s shooting touch immediately separates him. He’s a true stretch forward who knocks down threes with clean mechanics and confidence, whether spotting up from the trail, the slot, or the corners. He combines that shooting ability with real athletic pop — finishing above the rim, sprinting the floor, and attacking gaps with force when defenders close out too hard. What makes him even more valuable is his feel with the ball. Clingan is comfortable pushing the break, initiating sets, and making reads that most players his size simply can’t. There are flashes of point-forward instincts that hint at long-term upside once his handle tightens further. Defensively, he provides both rim protection and switchability. His length and timing allow him to anchor the paint, while his mobility gives him the versatility to hedge, recover, and survive on the perimeter when needed.With his rare blend of touch, mobility, and modern big-man versatility, Clingan projects as a matchup problem and a prospect whose stock should continue trending upward as he becomes more assertive physically.",
"
  },
  {
    id: "mj-ward-2026",
    name: "Mahliek “MJ” Ward",
    height: "6'1",
    position: "G",
    classYear: "2026",
    school: "Arkansas HS",
    state: "AR",
    stars: 4,
    summary:"Mahliek “MJ” Ward is one of the most complete and polished guards in the region — a high-IQ, two-way floor general whose game is defined by control, confidence, and elite skill. Ward operates with surgical precision. He dictates tempo, reads defenses like a veteran, and makes everything look effortless. Offensively, he’s dangerous at all three levels — armed with a smooth jumper and elite shot-making touch that ranks among the very best on the Watchlist. He’s arguably the top shooter and finisher among all guards listed, showcasing adaptive finishing instincts that allow him to score through contact, around length, and from multiple angles with either hand. Ward also has excellent feel as a playmaker, consistently finding teammates in transition or the half court, reading rotations early, and making the right play before the defense adjusts. Defensively, Ward sets the tone. He’s an elite on-ball defender who embraces tough assignments, using quick feet, anticipation, and discipline to completely take opposing guards out of rhythm. His IQ and communication make him a leader on that end, often anchoring the defensive energy for his team.Arguably the most skilled guard on the Watchlist, Ward’s maturity, balance, and competitive drive separate him. He plays chess while others play checkers — a true next-level guard built to win. With an improved physical frame, he could be extremely dangerous and further elevate his ceiling.",
  },
  {
    id: "jayden-tyeskie-2026",
    name: "Jayden Tyeskie",
    height: "6'4",
    position: "G",
    classYear: "2026",
    school: "Longview HS",
    state: "TX",
    stars: 4,
    summary:"Deadeye sniper. The ball barely touches the rim when he shoots. With a high release point and smooth mechanics, Tyeskie is one of the most dangerous shooters in East Texas. He can heat up quickly, punishing defenses with lethal one-dribble pull-ups, shot fakes, and jab steps to attack closeouts. High-IQ guard with excellent shot selection and a low turnover count — capable of filling it up when in rhythm. Defensively, his long, active arms stand out, constantly agitating ball handlers and big wings, creating disruption and tipping the balance in his team’s favor.",

  },
  {
    id: "anthony-spratt-jr-2028",
    name: "Anthony Spratt Jr.",
    height: "6'5",
    position: "G",
    classYear: "2028",
    school: "Benton HS",
    state: "AR",
    stars: 4,
  },

  // 3★
  {
    id: "jantz-alsup-2026",
    name: "Jantz Alsup",
    height: "6'6",
    position: "F",
    classYear: "2026",
    school: "South Central Prep",
    state: "OK",
    stars: 3,
  },
  {
    id: "greydon-howell-2027",
    name: "Greydon Howell",
    height: "5'10",
    position: "G",
    classYear: "2027",
    school: "Broken Bow",
    state: "OK",
    stars: 3,
  },
  {
    id: "carter-chism-2026",
    name: "Carter Chism",
    height: "5'11",
    position: "G",
    classYear: "2026",
    school: "Mt. Pleasant",
    state: "TX",
    stars: 3,
  },
  {
    id: "brian-cal-jr-2028",
    name: "Brian Cal Jr.",
    height: "6'1",
    position: "G",
    classYear: "2028",
    school: "Benton",
    state: "AR",
    stars: 3,
  },
  {
    id: "monti-mixon-2028",
    name: "Monti Mixon",
    height: "6'8",
    position: "F/C",
    classYear: "2028",
    school: "Nevada HS",
    state: "AR",
    stars: 3,
  },
  {
    id: "travis-gary-jr-2027",
    name: "Travis Gary Jr.",
    height: "5'10",
    position: "G",
    classYear: "2027",
    school: "Jefferson HS",
    state: "TX",
    stars: 3,
  },
  {
    id: "hudson-roberts-2028",
    name: "Hudson Roberts",
    height: "6'1",
    position: "G",
    classYear: "2028",
    school: "Redwater HS",
    state: "TX",
    stars: 3,
  },
  {
    id: "gavyn-young-2027",
    name: "Gavyn Young",
    height: "5'10",
    position: "G",
    classYear: "2027",
    school: "Kirby",
    state: "AR",
    stars: 3,
  },

  // 2★
  {
    id: "jordan-valentine-2026",
    name: "Jordan Valentine",
    height: "6'6",
    position: "G/F",
    classYear: "2026",
    school: "Choctaw",
    state: "OK",
    stars: 2,
  },
  {
    id: "javonte-ford-2026",
    name: "Javonte Ford",
    height: "6'4",
    position: "G/F",
    classYear: "2026",
    school: "Pleasant Hill",
    state: "LA",
    stars: 2,
  },
  {
    id: "matthew-widtfield-2027",
    name: "Matthew Widtfield",
    height: "6'3",
    position: "G",
    classYear: "2027",
    school: "Lucas Lovejoy",
    state: "TX",
    stars: 2,
  },
  {
    id: "bernard-zylan-2026",
    name: "Bernard Zylan",
    height: "6'5",
    position: "G/F",
    classYear: "2026",
    school: "Denton Ryan",
    state: "TX",
    stars: 2,
  },
  {
    id: "xavier-bazzelle-2026",
    name: "Xavier BazZelle",
    height: "5'11",
    position: "G",
    classYear: "2026",
    school: "Blevins",
    state: "AR",
    stars: 2,
  },
  {
    id: "zuo-kpogba-2026",
    name: "Zuo Kpogba",
    height: "6'2",
    position: "G",
    classYear: "2026",
    school: "Douglass HS",
    state: "OK",
    stars: 2,
  },
  {
    id: "colton-spence-2027",
    name: "Colton Spence",
    height: "6'11",
    position: "C",
    classYear: "2027",
    school: "McLeod",
    state: "TX",
    stars: 2,
  },
  {
    id: "cj-whaley-2028",
    name: "CJ Whaley",
    height: "6'6",
    position: "F/C",
    classYear: "2028",
    school: "Atlanta",
    state: "TX",
    stars: 2,
  },
  {
    id: "peyton-hicks-2026",
    name: "Peyton Hicks",
    height: "6'7",
    position: "F/C",
    classYear: "2026",
    school: "Genoa",
    state: "AR",
    stars: 2,
  },
  {
    id: "josiah-morales-2027",
    name: "Josiah Morales",
    height: "5'10",
    position: "PG",
    classYear: "2027",
    school: "Classen SAS",
    state: "OK",
    stars: 2,
  },
  {
    id: "ben-elam-2026",
    name: "Ben Elam",
    height: "6'2",
    position: "G",
    classYear: "2026",
    school: "Shattuck HS",
    state: "OK",
    stars: 2,
  },
  {
    id: "kristian-payne-2026",
    name: "Kristian Payne",
    height: "6'7",
    position: "F/C",
    classYear: "2026",
    school: "Grind Prep",
    state: "AR",
    stars: 2,
  },
  {
    id: "braylon-guerin-2026",
    name: "Braylon Guerin",
    height: "6'5",
    position: "G/F",
    classYear: "2026",
    school: "Northeast HS",
    state: "LA",
    stars: 2,
  },
  {
    id: "deunte-hamilton-2026",
    name: "Deunte Hamilton",
    height: "5'11",
    position: "G",
    classYear: "2026",
    school: "Magnolia",
    state: "AR",
    stars: 2,
  },
  {
    id: "isaiah-robinson-2026",
    name: "Isaiah Robinson",
    height: "6'3",
    position: "G/F",
    classYear: "2026",
    school: "El Dorado",
    state: "AR",
    stars: 2,
  },
  {
    id: "ty-palermo-2027",
    name: "Ty Palermo",
    height: "6'5",
    position: "G/F",
    classYear: "2027",
    school: "Lafayette",
    state: "LA",
    stars: 2,
  },
  {
    id: "zaybreion-cooper-2027",
    name: "Zaybreion Cooper",
    height: "5'10",
    position: "G",
    classYear: "2027",
    school: "Liberty-Eylau",
    state: "TX",
    stars: 2,
  },

  // 1★
  {
    id: "quincy-shelton-2026",
    name: "Quincy Shelton",
    height: "6'0",
    position: "G",
    classYear: "2026",
    school: "Hugo",
    state: "OK",
    stars: 1,
  },
  {
    id: "baker-hoskins-2026",
    name: "Baker Hoskins",
    height: "6'5",
    position: "F/C",
    classYear: "2026",
    school: "Idabel",
    state: "OK",
    stars: 1,
  },
  {
    id: "jason-webster-2027",
    name: "Jason Webster",
    height: "6'6",
    position: "G/F",
    classYear: "2027",
    school: "Jefferson",
    state: "TX",
    stars: 1,
  },
  {
    id: "micah-timmons-2027",
    name: "Micah Timmons",
    height: "6'1",
    position: "G",
    classYear: "2027",
    school: "Gladewater HS",
    state: "TX",
    stars: 1,
  },
  {
    id: "mason-lindsay-2026",
    name: "Mason Lindsay",
    height: "6'3",
    position: "G/F",
    classYear: "2026",
    school: "Kirby",
    state: "AR",
    stars: 1,
  },
  {
    id: "isaac-aaron-2026",
    name: "Isaac Aaron",
    height: "6'1",
    position: "G",
    classYear: "2026",
    school: "El Dorado",
    state: "AR",
    stars: 1,
  },
  {
    id: "kedrid-smith-2028",
    name: "Kedrid Smith",
    height: "6'5",
    position: "F/C",
    classYear: "2028",
    school: "Pleasant Grove",
    state: "TX",
    stars: 1,
  },
  {
    id: "devon-hall-clark-2027",
    name: "Devon Hall-Clark",
    height: "6'5",
    position: "F/C",
    classYear: "2027",
    school: "Liberty-Eylau",
    state: "TX",
    stars: 1,
  },
  {
    id: "adam-orr-2027",
    name: "Adam Orr",
    height: "6'2",
    position: "G/F",
    classYear: "2027",
    school: "Texas High",
    state: "TX",
    stars: 1,
  },
  {
    id: "javon-raye-2026",
    name: "Javon Raye",
    height: "6'4",
    position: "G/F",
    classYear: "2026",
    school: "ESTEM Charter",
    state: "AR",
    stars: 1,
  },
  {
    id: "holden-kirk-2026",
    name: "Holden Kirk",
    height: "6'4",
    position: "F",
    classYear: "2026",
    school: "ESTEM Charter",
    state: "AR",
    stars: 1,
  },
  {
    id: "landon-burley-2026",
    name: "Landon Burley",
    height: "6'0",
    position: "G",
    classYear: "2026",
    school: "Columbia Christian",
    state: "AR",
    stars: 1,
  },
  {
    id: "riley-jones-2026",
    name: "Riley Jones",
    height: "5'10",
    position: "G",
    classYear: "2026",
    school: "ESTEM Charter",
    state: "AR",
    stars: 1,
  },
  {
    id: "kingston-alexander-2026",
    name: "Kingston Alexander",
    height: "5'10",
    position: "G",
    classYear: "2026",
    school: "ESTEM Charter",
    state: "AR",
    stars: 1,
  },
  {
    id: "jace-sullivan-2026",
    name: "Jace Sullivan",
    height: "5'10",
    position: "G",
    classYear: "2026",
    school: "Mt. Pleasant Chapel Hill",
    state: "TX",
    stars: 1,
  },
  {
    id: "fabean-grigsby-2026",
    name: "Fabean Grigsby",
    height: "5'9",
    position: "G",
    classYear: "2026",
    school: "Hooks",
    state: "TX",
    stars: 1,
  },
  {
    id: "devaurionte-jackson-2026",
    name: "Devaurionte Jackson",
    height: "5'9",
    position: "G",
    classYear: "2026",
    school: "Liberty-Eylau",
    state: "TX",
    stars: 1,
  },
  {
    id: "jordan-hughey-2026",
    name: "Jordan Hughey",
    height: "5'10",
    position: "G",
    classYear: "2026",
    school: "Nevada County HS",
    state: "AR",
    stars: 1,
  },
  {
    id: "keyonte-wingfield-2026",
    name: "Keyonte Wingfield",
    height: "5'10",
    position: "G",
    classYear: "2026",
    school: "Nevada County HS",
    state: "AR",
    stars: 1,
  },
  {
    id: "javier-gomez-2026",
    name: "Javier Gomez",
    height: "5'10",
    position: "G",
    classYear: "2026",
    school: "Blevins",
    state: "AR",
    stars: 1,
  },
  {
    id: "keedan-adamson-2026",
    name: "Keedan Adamson",
    height: "6'0",
    position: "PG",
    classYear: "2026",
    school: "Paris HS",
    state: "TX",
    stars: 1,
  },
  {
    id: "kaydrien-henderson-2026",
    name: "KayDrien Henderson",
    height: "6'5",
    position: "F",
    classYear: "2026",
    school: "Paris HS",
    state: "TX",
    stars: 1,
  },
  {
    id: "nick-henderson-2026",
    name: "Nick Henderson",
    height: "5'9",
    position: "PG",
    classYear: "2026",
    school: "Western Heights",
    state: "OK",
    stars: 1,
  },
  {
    id: "jakyvian-hill-2026",
    name: "Jakyvian Hill",
    height: "6'2",
    position: "G",
    classYear: "2026",
    school: "Marshall HS",
    state: "TX",
    stars: 1,
  },
  {
    id: "victor-easter-2026",
    name: "Victor Easter",
    height: "6'0",
    position: "G",
    classYear: "2026",
    school: "Lake Hamilton HS",
    state: "AR",
    stars: 1,
  },
  {
    id: "javarious-russell-2026",
    name: "Javarious Russell",
    height: "5'11",
    position: "G",
    classYear: "2026",
    school: "Benton HS",
    state: "AR",
    stars: 1,
  },
  {
    id: "axl-janske-2028",
    name: "Axl Janske",
    height: "6'2",
    position: "PG",
    classYear: "2028",
    school: "Hot Springs Lakeside",
    state: "AR",
    stars: 1,
  },
  {
    id: "landon-woods-2026",
    name: "Landon Woods",
    height: "5'11",
    position: "G",
    classYear: "2026",
    school: "England HS",
    state: "AR",
    stars: 1,
  },
  {
    id: "aden-scribner-2026",
    name: "Aden Scribner",
    height: "6'5",
    position: "G/F",
    classYear: "2026",
    school: "England HS",
    state: "AR",
    stars: 1,
  },
  {
    id: "damien-vickz-2029",
    name: "Damien Vickz",
    height: "6'0",
    position: "G",
    classYear: "2029",
    school: "McLeod HS",
    state: "AR",
    stars: 1,
  },
  {
    id: "jaidyn-king-kirkindoff-2026",
    name: "Jaidyn King-Kirkindoff",
    height: "5'11",
    position: "G",
    classYear: "2026",
    school: "Longview HS",
    state: "TX",
    stars: 1,
  },
  {
    id: "caden-mcclain-2026",
    name: "Caden McClain",
    height: "5'10",
    position: "G",
    classYear: "2026",
    school: "Redwater HS",
    state: "TX",
    stars: 1,
  },

  // Extra names you listed but didn’t give full formatted fields for
  {
    id: "shawn-hall-2028",
    name: "Shawn Hall",
    height: "6'2",
    position: "G/F",
    classYear: "2028",
    school: "Liberty-Eylau HS",
    state: "TX",
    stars: 2,
  },
];
